name: Check version

on: [push]

jobs:
  check-repo-version:
    runs-on: ubuntu-latest
    steps:
    - name: check repo version
      run: |
        git clone https://github.com/stefanhaustein/TerminalImageViewer.git
        (
          cd TerminalImageViewer || exit 0
          git rev-parse HEAD
          git rev-parse HEAD^
          git checkout e5ef996c4432054c05e5af6965d405933c8391d1
        )